site_name: CS and GIS | Coding Journey
theme:
  name: material  # 使用你最喜欢的 Material 主题
  language: zh    # 设置界面为中文
  palette: 
    primary: indigo # 你可以改成 green, blue, teal 等你喜欢的颜色

nav:
  - 首页: index.md
  - 🌍 GIS 空间: GIS/index.md
  - 🐍 Python 笔记: python/index.md
  - 💻 C/C++ 编程: c_cpp/index.md
  - 🌐 前端开发: web_dev/index.md
  - 🛠️ 推荐工具: tools/index.md
